; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env:t-display-s3-amoled-plus]
platform = espressif32@6.12.0
board = T-Display-AMOLED
framework = arduino, espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series.git
    lvgl/lvgl @ 8.4.0
    lewisxhe/XPowersLib @ 0.2.7
    lewisxhe/SensorLib @ 0.2.4
lib_ignore =
    AceButton
    Adafruit NeoPixel
    GFX Library for Arduino
    SparkFun MAX3010x Pulse and Proximity Sensor Library
    TFT_eSPI
    TinyGPSPlus
build_flags =
    -Iinclude
    -DBOARD_HAS_PSRAM=1
    -DLV_CONF_PATH=lv_conf.h
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DDISABLE_ALL_LIBRARY_WARNINGS=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
